# Generated by Django 6.0.6 on 2026-06-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_date_posted_posts_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
